## Exercise 5.1

Given n, create a n x n matrix `M` of random values between 0 and 1. Multiply it by an Identity Matrix and verify that the result is unchanged from `M`.

$$
    M * I= M
$$

Numpy Functions that might come in handy here are `np.random.random`, `np.matmul`, `np.eye` and `np.allclose`.

In [3]:
import numpy as np

n = 5
# ----------------------- #
# COMPLETE THIS CODE
M = np.random.randn(n, n)
np.allclose(M @ np.eye(n), M)
# ----------------------- #

True

## Exercise 5.2

Given `m` and `n`, create two `m x n` matrices `A` and `B` of random values and verify the following mathematical identities:

$$
    (A + B)^{T} = A^{T} + B^{T}
$$
$$
    (AB)^{T} = B^{T}A^{T}
$$

Numpy Functions that might come in handy here are `np.random.random`, `np.matmul` and `np.allclose`. Also, remember that ndarrays have a `transpose()` *method*, or a `T` *property* that returns its transpose.

In [4]:
import numpy as np

m = 4
n = 5
# ----------------------- #
# COMPLETE THIS CODE
A = np.random.randn(m, n)
B = np.random.randn
np.allclose((A+B).T)
# ----------------------- #

[[ 0.67292202  1.52648213  0.63230217  0.3696448  -0.26612381]
 [-1.03305619  2.20614795  0.11802197  0.70551262  0.98834139]
 [-1.49298812  1.04219826 -0.05994208  1.58160267 -1.03507104]
 [-1.83039864  1.13072451 -0.00476259 -0.06446949 -0.67362205]]
